config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'portfolio-details/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank? }

    include Placeholder
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates_presence_of :title, :body, :main_image, :thumb_image

    def self.angular
        where(subtitle: "Angular")
    end

    scope :angular_portfolio_items, -> { where(subtitle: "Angular") }

    after_initialize :set_deafults

    def set_deafults
        self.main_image ||= Placeholder.image_generator('600', '400')
        self.thumb_image ||= Placeholder.image_generator('350', '200')
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolios"
    def index
        # @portfolio_items = Portfolio.angular
        # @portfolio_items = Portfolio.angular_portfolio_items
        @portfolio_items = Portfolio.all
    end

    def show
      @portfolio_items = Portfolio.friendly.find(params[:id])
    end

    def new
        @portfolio_items = Portfolio.new
        # 3.times do
        #   @portfolio_items.technologies.build
        # end
        3.times { @portfolio_items.technologies.build }
    end

    def create
        @portfolio_items = Portfolio.new(portfolio_params)
    
        respond_to do |format|
          if @portfolio_items.save
            format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
            format.json { render :show, status: :created, location: @blog }
          else
            format.html { render :new }
            format.json { render json: @blog.errors, status: :unprocessable_entity }
          end
        end
      end

      def edit
        @portfolio_items = Portfolio.friendly.find(params[:id])
      end

      def update
        @portfolio_items = Portfolio.friendly.find(params[:id])
        respond_to do |format|
          if @portfolio_items.update(portfolio_params)
            format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
          else
            format.html { render :edit }
          end
        end
      end

      def destroy
        @portfolio_items = Portfolio.friendly.find(params[:id])

        @portfolio_items.destroy
        respond_to do |format|
          format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private

      def portfolio_params
        params.require(:portfolio).permit(
          :title,
          :subtitle,
          :body,
          technologies_attributes: [:name]
        )
      end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Edit Portfolio</h1>

<%= render "forms", portfolio_items: @portfolio_items%>

app/views/portfolios/index.html.erb
<%= link_to 'Home', root_path %>
<h1>Portfolio Items</h1>

<%
=begin%>
 <a href="/portfolios/new">Create New Portfolio</a> 
<%
=end%>
<div>
<p id="notice"><%= notice %></p>

<%= link_to "Create New Portfolio", new_portfolio_path %>
</div>
<br>
<hr>
<br>
<% @portfolio_items.each do |item| %>
<%= image_tag item.thumb_image unless item.thumb_image.nil?%>
<p><%= item.title %></p>
<p><%= item.subtitle %></p>
<p><%= item.body %></p>
<%= link_to  "Edit", edit_portfolio_path(item) %>
<%= link_to  "Show", portfolio_show_path(item) %>
<br>
<hr>
<br>
<% end %>

app/views/portfolios/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New Portfolio</h1>
<%= render "forms", portfolio_items: @portfolio_items%>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @portfolio_items.main_image unless @portfolio_items.main_image.nil?%>
<p>
  <strong>Title:</strong>
  <%= @portfolio_items.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @portfolio_items.subtitle %>
</p>

<p>
  <strong>Body:</strong>
  <%= @portfolio_items.body %>
</p>


<% if @portfolio_items.technologies.count > 0 %>
  <h2>Technologies Used</h2>
<% end %>
<% @portfolio_items.technologies.each do |tech| %>
<p><%= tech.name %></p>
<% end %>

<%= link_to 'Edit', edit_portfolio_path(@portfolio_items) %>
<%= link_to 'Delete', @portfolio_items, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', portfolios_path %>